flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: lindas-barnard59
    - name: lindas-barnard59-base
    - name: lindas-barnard59-core
    - name: lindas-barnard59-csvw
    - name: lindas-barnard59-cube
    - name: lindas-barnard59-formats
    - name: lindas-barnard59-ftp
    - name: lindas-barnard59-graph-store
    - name: lindas-barnard59-http
    - name: lindas-barnard59-rdf
    - name: lindas-barnard59-sparql
    - name: lindas-barnard59-shacl
    - name: lindas-barnard59-validation
ignore:
  - test
  - "packages/*/test/**/*"
  - "packages/*/test/*"
